# x86_64-unknown-linux-gnu
[platform.linux-x86_64]
target_family = ["unix"]
target_os = ["linux"]
target_arch = ["x86_64"]
target_env = ["gnu"]
target_vendor = ["unknown"]

# aarch64-unknown-linux-gnu
[platform.linux-arm64]
target_family = ["unix"]
target_os = ["linux"]
target_arch = ["aarch64"]
target_env = ["gnu"]
target_vendor = ["unknown"]

# x86_64-apple-darwin (macOS, Intel-based)
[platform.macos-x86_64]
target_family = ["unix"]
target_os = ["macos"]
target_arch = ["x86_64"]
target_env = []
target_vendor = ["apple"]

# aarch64-apple-darwin (macOS, Apple silicon)
[platform.macos-arm64]
target_family = ["unix"]
target_os = ["macos"]
target_arch = ["aarch64"]
target_env = []
target_vendor = ["apple"]

# x86_64-pc-windows-msvc
[platform.windows-msvc]
target_family = ["windows"]
target_os = ["windows"]
target_arch = ["x86_64"]
target_env = ["msvc"]
target_vendor = ["pc"]

# x86_64-pc-windows-gnu
[platform.windows-gnu]
target_family = ["windows"]
target_os = ["windows"]
target_arch = ["x86_64"]
target_env = ["gnu"]
target_vendor = ["pc"]
target_abi = [] # not(target_abi = "llvm")
