# x86_64-unknown-linux-gnu
[platform.linux-x86_64]
x86_64-unknown-linux-gnu = []
target_arch = ["x86_64"]
target_endian = ["little"]
target_env = ["gnu"]
target_family = ["unix"]
target_feature = ["fxsr", "sse", "sse2"]
target_has_atomic = ["8", "16", "32", "64", "ptr"]
target_os = ["linux"]
target_pointer_width = ["64"]
target_vendor = ["unknown"]

# aarch64-unknown-linux-gnu
[platform.linux-arm64]
aarch64-unknown-linux-gnu = []
target_arch = ["aarch64"]
target_endian = ["little"]
target_env = ["gnu"]
target_family = ["unix"]
target_feature = ["neon"]
target_has_atomic = ["8", "16", "32", "64", "128", "ptr"]
target_os = ["linux"]
target_pointer_width = ["64"]
target_vendor = ["unknown"]

# x86_64-apple-darwin (macOS, Intel-based)
[platform.macos-x86_64]
x86_64-apple-darwin = []
target_arch = ["x86_64"]
target_endian = ["little"]
target_env = []
target_family = ["unix"]
target_feature = ["cmpxchg16b", "fxsr", "sse", "sse2", "sse3", "ssse3"]
target_has_atomic = ["8", "16", "32", "64", "128", "ptr"]
target_os = ["macos"]
target_pointer_width = ["64"]
target_vendor = ["apple"]

# aarch64-apple-darwin (macOS, Apple silicon)
[platform.macos-arm64]
aarch64-apple-darwin = []
target_arch = ["aarch64"]
target_endian = ["little"]
target_env = []
target_family = ["unix"]
target_feature = ["aes", "crc", "dit", "dotprod", "dpb", "dpb2", "fcma", "fhm", "flagm", "fp16", "frintts", "jsconv", "lor", "lse", "neon", "paca", "pacg", "pan", "pmuv3", "ras", "rcpc", "rcpc2", "rdm", "sb", "sha2", "sha3", "ssbs", "vh"]
target_has_atomic = ["8", "16", "32", "64", "128", "ptr"]
target_os = ["macos"]
target_pointer_width = ["64"]
target_vendor = ["apple"]

# x86_64-pc-windows-msvc
[platform.windows-msvc]
x86_64-pc-windows-msvc = []
target_arch = ["x86_64"]
target_endian = ["little"]
target_env = ["msvc"]
target_family = ["windows"]
target_feature = ["fxsr", "sse", "sse2"]
target_has_atomic = ["8", "16", "32", "64", "ptr"]
target_os = ["windows"]
target_pointer_width = ["64"]
target_vendor = ["pc"]

# x86_64-pc-windows-gnu
[platform.windows-gnu]
x86_64-pc-windows-gnu = []
target_arch = ["x86_64"]
target_endian = ["little"]
target_env = ["gnu"]
target_family = ["windows"]
target_feature = ["fxsr", "sse", "sse2"]
target_has_atomic = ["8", "16", "32", "64", "ptr"]
target_os = ["windows"]
target_pointer_width = ["64"]
target_vendor = ["pc"]
target_abi = [] # not(target_abi = "llvm")
